MyVensim: System Class Reference
System Class Reference
Representa um elemento de armazenamento dentro do modelo.
#include <System.h>
Public Member Functions
System ()
Construtor padrão.
System (double value)
Construtor com valor inicial.
System (const System &other)
Construtor de cópia.
System & operator= (const System &other)
Operador de atribuição.
virtual ~System ()
Destrutor virtual.
bool setValue (double v)
Define um novo valor para o sistema.
double getValue () const
Obtém o valor atual armazenado.
Private Attributes
double value
Valor atual armazenado pelo sistema.
Detailed Description
Representa um elemento de armazenamento dentro do modelo.
Um System contém um único valor numérico, que representa a quantidade atual de um recurso, população, nível, concentração etc., dependendo do contexto do modelo sendo simulado.
Essa classe é manipulada pela classe Model e pelos objetos Flow, que alteram seu valor ao longo da execução da simulação.
Definition at line 28 of file System.h.
Constructor & Destructor Documentation
System() [1/3]
System::System ()
Construtor padrão.
Inicializa o sistema com valor igual a 0.
Definition at line 17 of file System.cpp.
 : value(0.0) {}
System() [2/3]
System::System (double value)
Construtor com valor inicial.
Permite criar um System já com um valor definido.
Parameters
value Valor inicial do sistema.
Definition at line 19 of file System.cpp.
 : value(value) {}
System() [3/3]
System::System (const System & other)
Construtor de cópia.
Copia o valor de outro System.
Parameters
other Objeto System a ser copiado.
Definition at line 21 of file System.cpp.
 : value(other.value) {}
~System()
System::~System () virtual
Destrutor virtual.
Mantido virtual para permitir herança segura caso a classe seja estendida.
Definition at line 30 of file System.cpp.
 {}
Member Function Documentation
getValue()
double System::getValue () const
Obtém o valor atual armazenado.
Returns
O valor atual do System.
Definition at line 32 of file System.cpp.
{
     return value;
 }
References value.
Referenced by complexFuncionalTest(), ExponentialFlow::execute(), LogisticFlow::execute(), exponentialFuncionalTest(), logisticalFuncionalTest(), and Model::run().
operator=()
System & System::operator= (const System & other)
Operador de atribuição.
Substitui o valor atual pelo valor do outro System.
Parameters
other Objeto System a ser atribuído.
Returns
Referência para o próprio objeto.
Definition at line 23 of file System.cpp.
{
     if (this == &other)
         return *this;
     value = other.value;
     return *this;
 }
References value.
setValue()
bool System::setValue (double v)
Define um novo valor para o sistema.
Parameters
v Novo valor.
Returns
true se o valor foi definido com sucesso.
Definition at line 36 of file System.cpp.
{
     this->value = value;
     return true;
 }
References value.
Referenced by exponentialFuncionalTest(), and Model::run().
Member Data Documentation
value
double System::value private
Valor atual armazenado pelo sistema.
Este valor pode ser modificado diretamente pelo Model ou indiretamente pelos Flows durante a simulação.
Definition at line 36 of file System.h.
Referenced by getValue(), operator=(), and setValue().
The documentation for this class was generated from the following files:
src/System.h
src/System.cpp