MyVensim: Flow Class Reference
Flow Class Reference abstract
Classe base abstrata que define um fluxo entre dois Systems.
#include <Flow.h>
Public Member Functions
Flow ()
Construtor padrão.
Flow (System *source, System *target)
Construtor com parâmetros.
Flow (const Flow &flow)
Construtor de cópia.
virtual ~Flow ()
Destrutor virtual.
Flow & operator= (const Flow &other)
Operador de atribuição.
bool setSource (System *s)
Define o sistema de origem do fluxo.
System * getSource () const
Retorna o sistema de origem.
bool setTarget (System *t)
Define o sistema de destino do fluxo.
System * getTarget () const
Retorna o sistema de destino.
virtual double execute ()=0
Calcula o valor do fluxo neste passo de simulação.
Protected Attributes
System * source
Ponteiro para o sistema de origem.
System * target
Ponteiro para o sistema de destino.
Detailed Description
Classe base abstrata que define um fluxo entre dois Systems.
Cada Flow contém ponteiros para um System de origem e um System de destino. O Model utiliza objetos Flow para computar e aplicar transferências entre Systems em cada iteração da simulação.
Definition at line 29 of file Flow.h.
Constructor & Destructor Documentation
Flow() [1/3]
Flow::Flow ()
Construtor padrão.
Inicializa os ponteiros source e target como nullptr.
Definition at line 21 of file Flow.cpp.
 : source(nullptr), target(nullptr) {}
Flow() [2/3]
Flow::Flow (System * source, System * target)
Construtor com parâmetros.
Parameters
source Ponteiro para o System de origem (pode ser nullptr).
target Ponteiro para o System de destino (pode ser nullptr).
Definition at line 23 of file Flow.cpp.
     :source(source), target(target) {}
Flow() [3/3]
Flow::Flow (const Flow & flow)
Construtor de cópia.
Copia os ponteiros source/target (shallow copy). Se for necessário um comportamento de cópia profunda, implemente explicitamente na subclasse ou ajuste a política de propriedade.
Parameters
flow Objeto Flow a ser copiado.
Definition at line 28 of file Flow.cpp.
{
     if(this == &flow) return;
     source = flow.getSource();
     target = flow.getTarget();
 }
References getSource(), getTarget(), source, and target.
~Flow()
Flow::~Flow () virtual
Destrutor virtual.
Declarado virtual para permitir herança segura. Flow não assume propriedade (exclusive ownership) dos Systems apontados.
Definition at line 26 of file Flow.cpp.
 {};
Member Function Documentation
execute()
virtual double Flow::execute () pure virtual
Calcula o valor do fluxo neste passo de simulação.
Método abstrato que deve ser implementado por classes derivadas para definir a regra de transferência entre source e target.
Returns
Valor do fluxo calculado (double). A interpretação do valor depende da semântica do modelo (por ex.: taxa por unidade de tempo).
Implemented in LogisticFlow, and ExponentialFlow.
getSource()
System * Flow::getSource () const
Retorna o sistema de origem.
Returns
Ponteiro para o System de origem (pode ser nullptr).
Definition at line 40 of file Flow.cpp.
{
     return source;
 }
References source.
Referenced by ExponentialFlow::execute(), Flow(), operator=(), and Model::run().
getTarget()
System * Flow::getTarget () const
Retorna o sistema de destino.
Returns
Ponteiro para o System de destino (pode ser nullptr).
Definition at line 49 of file Flow.cpp.
{
     return target;
 }
References target.
Referenced by LogisticFlow::execute(), Flow(), operator=(), and Model::run().
operator=()
Flow & Flow::operator= (const Flow & other)
Operador de atribuição.
Realiza cópia segura dos ponteiros source e target.
Parameters
other Objeto a ser atribuído.
Returns
Referência para *this.
Definition at line 53 of file Flow.cpp.
{
     if(this == &flow)
         return *this;
     source = flow.getSource();
     target = flow.getTarget();
     return *this;
 }
References getSource(), getTarget(), source, and target.
setSource()
bool Flow::setSource (System * s)
Define o sistema de origem do fluxo.
Parameters
s Ponteiro para o System de origem. Pode ser nullptr para indicar que ainda não foi conectado.
Returns
true se a operação ocorreu com sucesso.
Definition at line 35 of file Flow.cpp.
{
     source = s;
     return true;
 }
References source.
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().
setTarget()
bool Flow::setTarget (System * t)
Define o sistema de destino do fluxo.
Parameters
t Ponteiro para o System de destino. Pode ser nullptr.
Returns
true se a operação ocorreu com sucesso.
Definition at line 44 of file Flow.cpp.
{
     target = t;
     return true;
 }
References target.
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().
Member Data Documentation
source
System* Flow::source protected
Ponteiro para o sistema de origem.
Definition at line 32 of file Flow.h.
Referenced by Flow(), getSource(), operator=(), and setSource().
target
System* Flow::target protected
Ponteiro para o sistema de destino.
Definition at line 35 of file Flow.h.
Referenced by Flow(), getTarget(), operator=(), and setTarget().
The documentation for this class was generated from the following files:
src/Flow.h
src/Flow.cpp