MyVensim: Model Class Reference
Model Class Reference
Classe responsável por gerenciar sistemas, fluxos e a simulação completa.
#include <Model.h>
Public Member Functions
Model ()
Construtor padrão.
Model (const Model &other)
Construtor de cópia.
Model & operator= (const Model &other)
Operador de atribuição.
~Model ()
Destrutor.
bool add (System *s)
Adiciona um novo sistema ao modelo.
bool add (Flow *f)
Adiciona um novo fluxo ao modelo.
bool remove (System *s)
Remove um sistema existente do modelo.
bool remove (Flow *f)
Remove um fluxo existente do modelo.
bool run (int startTime, int endTime)
Executa a simulação completa.
Protected Attributes
std::vector< System * > systems
Lista de sistemas pertencentes ao modelo.
std::vector< Flow * > flows
Lista de fluxos pertencentes ao modelo.
Detailed Description
Classe responsável por gerenciar sistemas, fluxos e a simulação completa.
O Model armazena dois conjuntos principais:
Uma lista de objetos System, representando entidades com um valor armazenado.
Uma lista de objetos Flow, que representem operações de transferência de valor entre Systems.
A função principal do Model é executar a simulação entre um tempo inicial e final, aplicando todos os fluxos existentes a cada passo.
Definition at line 37 of file Model.h.
Constructor & Destructor Documentation
Model() [1/2]
Model::Model ()
Construtor padrão.
Inicializa o modelo vazio, sem sistemas e sem fluxos.
Definition at line 22 of file Model.cpp.
 : systems(), flows() {}
Model() [2/2]
Model::Model (const Model & other)
Construtor de cópia.
Cria um novo Model copiando listas de sistemas e fluxos do modelo original.
Parameters
other Referência para o modelo a ser copiado.
Definition at line 27 of file Model.cpp.
{
     systems = other.systems;
     flows = other.flows;
 }
References flows, and systems.
~Model()
Model::~Model ()
Destrutor.
Realiza a limpeza das listas de Systems e Flows, quando necessário.
Definition at line 24 of file Model.cpp.
               {
 }
Member Function Documentation
add() [1/2]
bool Model::add (Flow * f)
Adiciona um novo fluxo ao modelo.
Parameters
f Ponteiro para o Flow a ser adicionado.
Returns
true se o fluxo foi adicionado com sucesso, false caso contrário.
Definition at line 46 of file Model.cpp.
{
     flows.push_back(f);
     return true;
 }
References flows.
add() [2/2]
bool Model::add (System * s)
Adiciona um novo sistema ao modelo.
Parameters
s Ponteiro para o System a ser adicionado.
Returns
true se o sistema foi adicionado com sucesso, false caso contrário.
Definition at line 41 of file Model.cpp.
{
     systems.push_back(s);
     return true;
 }
References systems.
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().
operator=()
Model & Model::operator= (const Model & other)
Operador de atribuição.
Permite copiar modelos de forma segura, substituindo o conteúdo atual.
Parameters
other Modelo a ser atribuído.
Returns
Referência para o objeto atual, após a operação.
Definition at line 32 of file Model.cpp.
{
     if (this == &other)
         return *this;
     systems = other.systems;
     flows = other.flows;
     return *this;
 }
References flows, and systems.
remove() [1/2]
bool Model::remove (Flow * f)
Remove um fluxo existente do modelo.
Parameters
f Ponteiro para o Flow a ser removido.
Returns
true se o fluxo foi removido, false caso contrário.
Definition at line 60 of file Model.cpp.
{
     auto it = find(flows.begin(), flows.end(), f);
     if (it != flows.end()) {
         flows.erase(it);
         return true;
     }
     return false;
 }
References flows.
remove() [2/2]
bool Model::remove (System * s)
Remove um sistema existente do modelo.
Parameters
s Ponteiro para o System a ser removido.
Returns
true se o sistema foi removido, false caso contrário.
Definition at line 51 of file Model.cpp.
{
     auto it = find(systems.begin(), systems.end(), s);
     if (it != systems.end()) {
         systems.erase(it);
         return true;
     }
     return false;
 }
References systems.
run()
bool Model::run (int startTime, int endTime)
Executa a simulação completa.
Executa a simulação do modelo entre dois instantes de tempo.
A simulação ocorre aplicando todos os fluxos do modelo entre as iterações de tempo fornecidas. O comportamento detalhado depende da implementação de cada tipo concreto de Flow.
Parameters
startTime Tempo inicial da simulação.
endTime Tempo final da simulação.
Returns
true se a simulação ocorreu normalmente, false caso haja falhas.
Este método percorre o intervalo de tempo definido por startTime e endTime, calculando primeiro o valor de todos os fluxos e depois aplicando esses valores aos sistemas associados. O processo ocorre em duas etapas a cada ciclo:
Cálculo dos fluxos: cada Flow executa seu método execute(), cujo resultado é armazenado em um vetor temporário.
Isso garante que todos os fluxos sejam calculados antes de alterar qualquer System.
Atualização dos sistemas: para cada fluxo, subtrai-se o valor do fluxo do sistema de origem (source) e adiciona-se ao sistema de destino (target), caso existam.
Essa abordagem evita dependências indesejadas entre fluxos e garante consistência durante a simulação.
Parameters
startTime Tempo inicial da simulação (inteiro).
endTime Tempo final da simulação (inteiro). A simulação ocorre enquanto time < endTime.
Returns
true se a simulação foi executada com sucesso.
Definition at line 95 of file Model.cpp.
{
     for (int time = startTime; time < endTime; time++) {
         int n = flows.size();
         vector<double> results(n);
         for (int i = 0; i < n; i++)
             results[i] = flows[i]->execute();
         for (int i = 0; i < n; i++) {
             Flow* f = flows[i];
             if (f->getSource())
                 f->getSource()->setValue(f->getSource()->getValue() - results[i]);
             if (f->getTarget())
                 f->getTarget()->setValue(f->getTarget()->getValue() + results[i]);
         }
     }
     return true;
 }
References flows, Flow::getSource(), Flow::getTarget(), System::getValue(), and System::setValue().
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().
Member Data Documentation
flows
std::vector<Flow*> Model::flows protected
Lista de fluxos pertencentes ao modelo.
Cada objeto Flow define como os valores dos sistemas passam de um para outro.
Definition at line 51 of file Model.h.
Referenced by add(), Model(), operator=(), remove(), and run().
systems
std::vector<System*> Model::systems protected
Lista de sistemas pertencentes ao modelo.
Cada ponteiro armazena um objeto do tipo System que participa da simulação.
Definition at line 44 of file Model.h.
Referenced by add(), Model(), operator=(), and remove().
The documentation for this class was generated from the following files:
src/Model.h
src/Model.cpp