MyVensim: test/funcional/main.cpp File Reference
main.cpp File Reference
Arquivo principal responsável por executar os testes funcionais do simulador.
#include "funcional_tests.h"
#include "../../src/Model.h"
#include "../../src/Flow.h"
#include <assert.h>
Functions
int main (void)
Detailed Description
Arquivo principal responsável por executar os testes funcionais do simulador.
Este arquivo contém apenas a função main(), cuja função é chamar os testes funcionais implementados em functional_tests.cpp. Ele serve como ponto de entrada para validar o comportamento do simulador completo, verificando a interação entre Model, System e Flow por meio dos cenários definidos nos testes.
A execução inclui:
Teste funcional exponencial.
Teste funcional logístico.
Teste funcional complexo envolvendo múltiplos fluxos.
Cada teste utiliza asserts para verificar se o simulador está produzindo resultados consistentes e matematicamente corretos.
Author
Samuel
Date
2025
Definition in file main.cpp.
Function Documentation
main()
int main (void)
Definition at line 32 of file main.cpp.
               {
     exponentialFuncionalTest();
     logisticalFuncionalTest();
     complexFuncionalTest();
 }
References complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().